# Generated by Django 2.0.3 on 2018-05-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podstrony', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Budowa',
        ),
    ]
