# Generated by Django 2.0.3 on 2018-06-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podstrony', '0005_image_meteorologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='budowa',
            name='img',
            field=models.ImageField(blank=True, upload_to='budowa_image'),
        ),
    ]
