# Generated by Django 2.0.3 on 2018-05-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_auto_20180520_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_meteo',
            name='id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
