# Generated by Django 2.0.3 on 2018-05-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_auto_20180520_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer_Meteo',
        ),
    ]
