"""
Django settings for strona_zagle project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) #katalog projektu


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'jd%9$p0k6lk2!3^z$b^v29#qt)sww$crb_8=u+qju4sld7rl+v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True #Jeśli projekt jest rozwijany, to opcja ta jest ustawiona na True

ALLOWED_HOSTS = [] # Jakie adresy internetowe mają dostęp do tej aplikcji


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin', #panel administracyjny
    'django.contrib.auth',  #aplikacja zajmująca się autoryzacją użytkowników
    'django.contrib.contenttypes', #umożliwia tworzenie relacji pomiędzy dowolnymi obiektami w bazie (innym niż w bazie danych)
    'django.contrib.sessions', # odpowiedzialna za obsługę sesji, cookies
    'django.contrib.messages', # służy do wyświetlania komunikatów dla użytkownika
    'django.contrib.staticfiles', # służy do zarządzania plikami statycznymi np. layout
    'shelf', # Aby dodać coś do bazy danych, należy tutaj dopisać utworzoną aplikację.
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'strona_zagle.urls' #ścieżka do pliku opisującgo strukturę url

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'strona_zagle.wsgi.application' # Co ma się stać kiedy uruchamiamy aplikacje w trybie serwerowym


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases
# Konfiguracja bazy danych
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'pl' # kod języka w jakim strona ma się komunikować

TIME_ZONE = 'Europe/Warsaw' # strefa czasowa - UTC -> czas lokalny

# Dwie zmienne, które odpowiadają za to, że nasz projetk będzie się komunikował w naszym języku
USE_I18N = True # Internationalization - pomiędzy I a N jest 18 liter

USE_L10N = True # localization

USE_TZ = True # Use TimeZone - czy ma używać stref czasowych


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/' # Pod jakim adresem będą dostępne pliki statyczne

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(BASE_DIR, 'templates')),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # Insert your TEMPLATE_CONTEXT_PROCESSORS here or use this
                # list if you haven't customized them:
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]